import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import { saveConfig, getConfigDir } from '../src/config.js';
import { isGatewayHealthy } from '../src/gateway/detect.js';
import { logger } from '../src/logger.js';
import { PROVIDERS } from '../src/helpers/constants.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GATEWAY_DIR = path.resolve(__dirname, '../gateway');

export async function runSetup() {
  logger.info('Setup wizard started');
  console.log(chalk.bold.cyan('\n  council setup\n'));

  // 1. Check Docker
  const dockerSpinner = ora('Checking Docker…').start();
  try {
    execSync('docker info', { stdio: 'ignore' });
    logger.info('Docker is running');
    dockerSpinner.succeed('Docker is running');
  } catch {
    logger.warn('Docker not running — will use SDK-only mode');
    dockerSpinner.fail('Docker is not running');
    console.log(chalk.yellow('\n  Docker is required to use the LiteLLM gateway.'));
    console.log(chalk.gray('  Install Docker Desktop: https://docs.docker.com/get-docker/\n'));
    console.log(chalk.gray('  Proceeding with SDK-only mode (OpenAI/Anthropic/Gemini only).\n'));
  }

  // 2. Provider selection
  const { selectedProviders } = await inquirer.prompt([
    {
      type: 'checkbox',
      name: 'selectedProviders',
      message: 'Which providers do you want to enable?',
      choices: PROVIDERS.map((p) => ({
        name: p.name,
        value: p.value,
        checked: p.value !== 'ollama',
      })),
    },
  ]);

  if (selectedProviders.length === 0) {
    logger.warn('Setup aborted — no providers selected');
    console.log(chalk.red('\n  At least one provider is required. Exiting.\n'));
    process.exit(1);
  }

  // 3. API keys
  const keys = {};
  for (const providerValue of selectedProviders) {
    const provider = PROVIDERS.find((p) => p.value === providerValue);
    if (!provider.envKey) continue;

    const { key } = await inquirer.prompt([
      {
        type: 'text',
        name: 'key',
        message: `${provider.name} API key:`,
        validate: (v) => v.trim().length > 0 || 'API key cannot be empty',
      },
    ]);
    keys[provider.envKey] = key.trim();
  }

  // 4. Build config
  const models = PROVIDERS.filter((p) => selectedProviders.includes(p.value)).map((p) => ({
    id: p.modelId,
    label: p.label,
    enabled: true,
  }));

  const config = {
    gateway: { baseUrl: 'http://localhost:4000', apiKey: 'sk-council-local' },
    models,
    keys,
  };

  logger.info('Providers selected', { providers: selectedProviders });

  // 5. Write ~/.council/config.json
  const configSpinner = ora('Writing config…').start();
  saveConfig(config);
  logger.info('Config saved', { path: `${getConfigDir()}/config.json` });
  configSpinner.succeed(`Config saved to ${getConfigDir()}/config.json`);

  // 6. Generate litellm_config.yaml
  const yamlSpinner = ora('Generating gateway config…').start();
  const yamlModels = PROVIDERS.filter((p) => selectedProviders.includes(p.value))
    .map((p) => {
      if (p.value === 'ollama') {
        return `  - model_name: ${p.modelId}\n    litellm_params:\n      model: ${p.modelId}\n      api_base: http://host.docker.internal:11434`;
      }
      return `  - model_name: ${p.modelId}\n    litellm_params:\n      model: ${p.modelId}\n      api_key: os.environ/${keys[p.envKey]}`;
    })
    .join('\n\n');

  const litLLMYaml = `# Generated by \`council setup\`\nmodel_list:\n${yamlModels}\n\ngeneral_settings:\n  master_key: sk-council-local\n`;
  fs.writeFileSync(path.join(GATEWAY_DIR, 'litellm_config.yaml'), litLLMYaml, 'utf8');
  logger.info('litellm_config.yaml written', {
    path: path.join(GATEWAY_DIR, 'litellm_config.yaml'),
  });
  yamlSpinner.succeed('Gateway config written');

  // 7. Health check gateway
  const gatewaySpinner = ora('Testing gateway health…').start();
  const healthy = await isGatewayHealthy('http://localhost:4000');
  if (healthy) {
    logger.info('Gateway already healthy at setup time');
    gatewaySpinner.succeed('Gateway is already running and healthy');
  } else {
    logger.info('Gateway not yet running — will start on next council launch');
    gatewaySpinner.info('Gateway not running yet — will start automatically on `council`');
  }

  logger.info('Setup wizard complete');
  console.log(chalk.bold.green('\n  Setup complete! Run `council` to start.\n'));
}
